services:
    versia:
        image: ghcr.io/versia-pub/server:main
        volumes:
            - ./logs:/app/dist/logs
            - ./config:/app/dist/config:ro
            - ./uploads:/app/dist/uploads
        restart: unless-stopped
        container_name: versia
        tty: true
        networks:
            - versia-net
        depends_on:
            - db
            - redis
            - sonic

    worker:
        image: ghcr.io/versia-pub/worker:main
        volumes:
            - ./logs:/app/dist/logs
            - ./config:/app/dist/config:ro
        restart: unless-stopped
        container_name: versia-worker
        tty: true
        networks:
            - versia-net
        depends_on:
            - db
            - redis

    db:
        image: postgres:17-alpine
        container_name: versia-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: versia
            POSTGRES_USER: versia
            POSTGRES_PASSWORD: versia
        networks:
            - versia-net
        volumes:
            - ./db-data:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        container_name: versia-redis
        volumes:
            - ./redis-data:/data
        restart: unless-stopped
        networks:
            - versia-net

    sonic:
        volumes:
            - ./config.cfg:/etc/sonic.cfg
            - ./store:/var/lib/sonic/store/
        image: valeriansaliou/sonic:v1.4.9
        container_name: versia-sonic
        restart: unless-stopped
        networks:
            - versia-net

networks:
    versia-net:
