packages:
    - packages/*

onlyBuiltDependencies:
    - esbuild
    - msgpackr-extract
    - sharp

shamefullyHoist: true
catalog:
    {
        "@biomejs/biome": "2.0.0-beta.5",
        "@types/bun": "^1.2.16",
        "@types/html-to-text": "^9.0.4",
        "@types/markdown-it-container": "^2.0.10",
        "@types/mime-types": "^3.0.1",
        "@types/qs": "^6.14.0",
        "@types/web-push": "^3.6.4",
        "bun-bagel": "^1.2.0",
        "drizzle-kit": "^0.31.1",
        "mitt": "^3.0.1",
        "markdown-it-image-figures": "^2.1.1",
        "ts-prune": "^0.10.3",
        "typescript": "^5.8.3",
        "vitepress": "^1.6.3",
        "vitepress-plugin-tabs": "^0.7.1",
        "vitepress-sidebar": "^1.31.1",
        "vue": "^3.5.16",
        "zod-to-json-schema": "^3.24.5",
        "@bull-board/api": "^6.10.1",
        "@bull-board/hono": "^6.10.1",
        "@clerc/plugin-completions": "^0.44.0",
        "@clerc/plugin-friendly-error": "^0.44.0",
        "@clerc/plugin-help": "^0.44.0",
        "@clerc/plugin-not-found": "^0.44.0",
        "@clerc/plugin-version": "^0.44.0",
        "@hackmd/markdown-it-task-lists": "^2.1.4",
        "@hono/zod-validator": "^0.7.0",
        "@inquirer/confirm": "^5.1.12",
        "@logtape/file": "^0.12.0",
        "@logtape/logtape": "^0.12.0",
        "@scalar/hono-api-reference": "^0.9.4",
        "@sentry/bun": "^9.29.0",
        "altcha-lib": "^1.3.0",
        "blurhash": "^2.0.5",
        "bullmq": "^5.53.3",
        "chalk": "^5.4.1",
        "clerc": "^0.44.0",
        "confbox": "^0.2.2",
        "drizzle-orm": "^0.44.2",
        "feed": "^5.1.0",
        "hono": "^4.7.11",
        "hono-openapi": "^0.4.8",
        "hono-rate-limiter": "^0.4.2",
        "html-to-text": "^9.0.5",
        "ioredis": "^5.6.1",
        "ip-matching": "^2.1.2",
        "iso-639-1": "^3.1.5",
        "jose": "^6.0.11",
        "linkify-html": "^4.3.1",
        "linkify-string": "^4.3.1",
        "linkifyjs": "^4.3.1",
        "magic-regexp": "^0.10.0",
        "markdown-it": "^14.1.0",
        "markdown-it-anchor": "^9.2.0",
        "markdown-it-container": "^4.0.0",
        "markdown-it-mathjax3": "^4.3.2",
        "markdown-it-toc-done-right": "^4.2.0",
        "mime-types": "^3.0.1",
        "mitata": "^1.0.34",
        "oauth4webapi": "^3.5.2",
        "ora": "^8.2.0",
        "qs": "^6.14.0",
        "sharp": "^0.34.2",
        "sonic-channel": "^1.3.1",
        "string-comparison": "^1.3.0",
        "stringify-entities": "^4.0.4",
        "unicode-emoji-json": "^0.8.0",
        "uqr": "^0.1.2",
        "web-push": "^3.6.7",
        "xss": "^1.0.15",
        "youch": "^4.1.0-beta.7",
        "zod": "^3.25.64",
        "zod-openapi": "^4.2.4",
        "zod-validation-error": "^3.5.0",
    }
