name: Test Publish

on:
    push:

permissions:
    contents: read
    # For provenance generation
    id-token: write

jobs:
    # Build job
    build:
        runs-on: ubuntu-latest
        environment: NPM Deploy
        strategy:
            matrix:
                package: ["sdk", "client"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2

            - name: Install
              run: bun install --frozen-lockfile

            - name: Publish to NPM
              working-directory: packages/${{ matrix.package }}
              env:
                  NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: bun publish --dry-run --access public

            - name: Publish to JSR
              working-directory: packages/${{ matrix.package }}
              run: bunx jsr publish --allow-slow-types --allow-dirty --dry-run
