name: Test Publish

on:
    push:

permissions:
    contents: read
    # For provenance generation
    id-token: write

jobs:
    # Build job
    build:
        runs-on: ubuntu-latest
        environment: NPM Deploy
        strategy:
            matrix:
                package: ["sdk", "client"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2

            - name: Install
              run: bun install

            - name: Configure .npmrc
              working-directory: packages/${{ matrix.package }}
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

            - name: Publish to NPM
              working-directory: packages/${{ matrix.package }}
              run: bun publish --dry-run

            - name: Publish to JSR
              working-directory: packages/${{ matrix.package }}
              run: bunx jsr publish --allow-slow-types --allow-dirty --dry-run
